# Site settings
title: Maason Kao
email: maasongmx@gmail.com
description: > # keep this and put description below
  Programmer and Designer
url: "https://maasonkao.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/maasonkao"
github_username: maasonkao
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
